# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be79890bed7823329e8c6ecb8897d00eedf135551d71d62b56edc9b1be6e49f8705a05bac70b5a059b24229f44b23cea58774e6d07d78e09943f24dd2891554f

test:
  secret_key_base: 8baccbec3168ef0fe5ff32bb3056fb521de62998a0e2d6273a6a2539d9d67111258d60cf8c78d40f72563f6392498ac085f989e07fc8d4ec0045c59bd7eaaf4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
